export const STORAGE_KEYS = {
  PETS: '@petcare:pets',
  PET_ATIVO: '@petcare:pet_ativo',
  EVENTOS: '@petcare:eventos',
  ONBOARDING_CONCLUIDO: '@petcare:onboarding',
  NOTIFICACOES: '@petcare:notificacoes',
  SESSAO: '@petcare:sessao',
  SESSAO_ENCERRADA: '@petcare:sessao_encerrada',
  CONTAS_CONHECIDAS: '@petcare:contas_conhecidas',
  RECOMPENSAS: '@petcare:recompensas',
  VETERINARIOS: '@petcare:veterinarios',
  VETERINARIO_ATIVO: '@petcare:veterinario_ativo',
  DISPONIBILIDADE: '@petcare:disponibilidade',
  BLOQUEIOS_AGENDA: '@petcare:bloqueios_agenda',
};